import type { Metadata } from "next";
import { Jost } from "next/font/google";

import Header from "@/components/header/header";

import Footer from "@/components/footer/footer";
import LetsTalk from "@/components/footer/lets-talk";
import "./globals.css";

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Designo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased max-w-[90rem] max-h-dvh`}>
        <Header />
        <div className="px-6 sm:px-10 xl:px-[10.31rem]">{children}</div>
        <LetsTalk />
        <Footer />
      </body>
    </html>
  );
}
