import type { Metadata } from "next";
import { Jost } from "next/font/google";

import Footer from "@/components/footer";
import Header from "@/components/header";

import "./globals.css";

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Designo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} relative antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
